repos:

- repo: local
  hooks:
  - id: pip-compile
    name: compile api/requirements.txt
    entry: pip-compile
    language: system
    always_run: false
    args: [-p, -o, '-P', 'OZI', api/requirements.txt]
    files: api/requirements.in
    stages: [push]
