# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev34+gf4b7ca5.d20230714'
__version_tuple__ = version_tuple = (0, 1, 'dev34', 'gf4b7ca5.d20230714')
