[tool.semantic_release]
branch = "main"
build_command = """
git stash && \
python -m build -w && \
git stash -- PKG-INFO && \
python -m pyc_wheel dist/*.whl && \
meson setup dist/build && \
git stash drop && \
git add PKG-INFO && \
git commit PKG-INFO -m \":loud_sound: Added release changes and updated PKG-INFO.\" && \
meson dist -C dist/build --formats gztar --no-tests --allow-dirty && \
sigstore sign dist/*.whl dist/build/meson-dist/*.tar.gz && \
git stash pop && \
git add CHANGELOG.md && \
git commit --amend --noedit && \
git stash clear"""
changelog_file = "CHANGELOG.md"
changelog_placeholder = "<!--next-version-placeholder-->"
commit_version_number = true
dist_glob_patterns = "*.dist-info,*.whl,build/meson-dist/*.tar.gz"
